### ISSUE TITLE
Time Stamp Proofs

### ISSUE THREAD

**Issue by burnburn** [w3c/did-use-cases#1]
Issue taken over from the CCG (https://github.com/w3c-ccg/did-use-cases/issues/3)

**Comment by burnburn** [comment]
Commenters in the CCG were @ChristopherA @jandrieu

**Comment by jandrieu** [comment]
@ChristopherA wrote (in the CCG issue):
> For long-term credentials, for instance in the Educational use case, the fact that most DIDs include strong time stamps, that Verifiable Credentials can also do them as well, as well as some status/revocation also do, means that you can make statements that the claim was valid when issued and for a period of time. Even if the issuer disappears or rotates their own keys, this may be sufficient to validate the DID & Credentials in some scenarios.

Christopher, would you like to suggest an edit? Either to a current use case or proposing a new one?

**Comment by philarcher** [comment]
This issue remains open (from waaay back). @jandrieu and I are likely to close it without action in the absence of further discussion, notably (but not exclusively) from @ChristopherA

**Comment by jandrieu** [comment]
+1 to closing. I think the use case idea of "timestamps" is too vague to turn into a PR. Also, it's not clear that timestamps affect the design or functionality of DIDs. Not all DID methods can provide cryptographically reliable timestamps, so both the use value for the individual and the architectural implications are unclear.
