### ISSUE TITLE
Synchronize DID role terminology between Use Cases and Core specs

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#10]
Section 2 of the Use Cases (What can you do with a DID?) defines three entities for working with DIDs:  The Controller, the Relying Party, and the Subject.  This seems highly related to https://github.com/w3c/did-core/issues/4 - which is about defining terms for three DID roles.

The terms for these roles should be kept in sync between the specifications as they evolve.

**Comment by philarcher** [comment]
As discussed by the WG [2019-11-12](https://www.w3.org/2019/11/12-did-minutes#item04) there will be a single terms document that will be included automatically in both the UCR and the Core spec (and maybe other docs). The FPWD, however, will use a snapshot that highlights this future state and the current open issues.
