### ISSUE TITLE
Add human story for 2.1 online shopper

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-use-cases#105]
Rather than just presenting generalities, I'd like to consider adding or simply using something like the following for the use case currently known as 2.1 Online Shopping

> 2.1 Online product verification
> Merry has been seeking a special edition, collectible card ever since her best friend, Eli, opined about losing the one his Dad had given him as a reward for getting straight "A"s in 4th grade. She found it on an online marketplace, for sale by DeepVintage in another country, over 2000 miles away. Although the marketplace promises refunds, Merry is also worried that Eli's heart would be broken if she accidentally got him a fake. 
> 
> Fortunately, DeepVintage is able to provide documentation in the form of signed statements of title transfer from each of the owners, all the way back to the original, which includes a statement of authenticity from the original manufacturer. Each of the signed statements can be independently verified because they were signed using public DIDs for the buyer and seller. The collected signatures comprise a complete chain of custody along with some interesting anecdotes about each sale. Merry was able to verify the provenance of the card and delighted Eli with a surprise gift of a perfect replacement for his lost memento.

**Comment by philarcher** [comment]
This has been done!
