### ISSUE TITLE
Add human story for 2.1 Vehicle assemblies

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-use-cases#106]
Rather than just presenting generalities, I'd like to consider adding or simply using something like the following for the use case currently known as 2.2 Vehicle Assemblies
 
> 2.2 Vehicles and assemblies
> When Bertha bought her new car, it came with its own DID, not just as an alternative VIN, but with unique DIDs for every replaceable component in the vehicle and a secure data storage for keeping track of vehicle use and maintenance. Even before she purchased it, she was able to verify that, as advertised, every part in the car is 100% made with carbon-neutral processes. 
> 
> As the controller of the car's DID, she had automatic control over all of its component's DIDs.  During maintenance, she would choose mechanics that automatically provided digital records of their work, stored at her direction in the car's data store. When a part needed to be replaced, she'd make sure the new component's DID is recorded and the old one retired. Similarly, her car automatically tracked fuel purchases and saved telemetry reports to storage, where it was kept securely under her control. 
>  
> She found an insurance company that was able to automatically offer her a discount after passing a certification of good maintenance and good driving. When she later put her car up for sale, she was able to prove her track record of maintenance. Upon sale, she transferred control over the car's DID and its secure storage, giving the new owner a working, and contiguous record of the vehicle.

**Comment by philarcher** [comment]
This has been done!
