### ISSUE TITLE
Consider removing use case 2.4

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-use-cases#108]
As I attempted to categorize the existing use cases into domains, I found use case **2.4 Accessing Master Data of Entities** to be exceptionally generic and, ultimately, vague about just what kind of value is being created for whom.

For other use cases I was able to write up a human story that personalized the use and made it real to the average reader. However, this one was so non-specific it was hard to understand what made it different than say 2.3 Vehicle Assemblies, both of which are essentially about reliable records of a persistent yet complex entity.

Is there something we could still distill to add a human touch? 

If not, we might be better of removing it.

**Comment by philarcher** [comment]
I sympathize. However, I know this went through a lot of internal review at Robert Bosch GmbH and so ts removal, especially at this late stage, would be problematic. I'm inclined to leave it well alone. Life ain't always perfect.

**Comment by jandrieu** [comment]
Ok. I can support that.
