### ISSUE TITLE
Add human story to 2.5 Identifiers in an ecosystem of verifiable credentials (VCs):

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-use-cases#109]
Rather than just presenting generalities, I'd like to consider adding or simply using something like the following for the use case currently known as 2.5 Identifiers in an ecosystem of verifiable credentials (VCs):
> 2.5 Robust Identifiers for verifiable credentials (VCs)
Dixon's employer uses DIDs and VCs to track workplace successes and recognition. Every employee has a DID registered with the company and accessible via the company registry. When he completes a training program—like CPR or Export Compliance--or receives an accolade like employee of the month, the company mints a new Verifiable Credential. These are not only used by HR in their evaluations for raises and bonuses, they are all made available to Dixon in a form he can use outside the firm. He maintains a career portfolio on his own server which he uses to keep track of his career.
>
> When a devastating Earthquake nearly destroyed half of his small town, Dixon was able to present a selection of his workplace credentials to the office of the Incident Commander, establishing his expertise in disaster response. He used the proof material associated with the DID to prove that he was the recipient of those credentials. He was immediately put to work helping people recover from the disaster.
> 
> Over the years, following corporate policy, he updates his cryptographic material for his workplace DID. After these updates, all of the credentials could still be verified as having been issued to Dixon.

**Comment by philarcher** [comment]
I've created the PR although I think it suffers from being rather too far-fetched. Forward-looking is fine, but this is bordering on fantasy. When you invoke a earthquake as part of a use case... it's a little off the (seismic) chart.
