### ISSUE TITLE
Use Cases document missing References section

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#11]
There's a number of places in the Use Cases document that refer to other specifications without providing references to them.  First, a References section needs to be added.  Then entries in it need to be filled in and used when the spec alludes to other documents such a "DID Resolution" specification and a "DID Auth" specification.

**Comment by peacekeeper** [comment]
+1 to adding a References section. See https://github.com/w3c/did-use-cases/issues/15 for comments about "DID Resolution". For "DID Auth", there is no single specification, but there are some papers out there that we should probably reference in the Use Cases doc.
