### ISSUE TITLE
Add a human story to use case 2.6 Sharing opted-in information across platforms

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-use-cases#110]
Rather than just presenting generalities, I'd like to consider adding or simply using something like the following for the use case currently known as  2.6 Sharing opted-in information across platforms:
> Franklyn is frustrated by the seemingly endless surveillance that tracks his activity online. He is a single father of two girls whose privacy is absolutely vital to him. He does what he can to minimize the ways in which he might accidentally put his kids at risk, avoiding sharing details of his life, his shopping, or the inadvertent geo-located digital photo. He has minimized her digital footprint and opted out of everything but the most secure and privacy respecting sites.
> 
> However, when he can verify that a website is meeting his own standards for privacy and is willing to accept a fiduciary obligation to protect her and her information, he appreciates the personalized services that can be created by sharing select nuggets of information while remaining as anonymous as possible. 
> 
> For each service, he creates a new unique DID and authorizes the company to use it to track him, as long as they have agreed to his specific terms of service, which covers inappropriate use of his data, whether internally or in redistributing it to other companies. With this unique identifier, the services are able to build up a history of interactions with Franklyn, without recourse to his legal identity, IP address, any credit or income data, nothing. Just the DID. By authenticating using the DID the service has an exceptionally strong assurance that the current session is Franklyn. Should the store data become compromised in a data breach, all the attackers will get is a history of shopping and shopping lists associated with an arbitrary DID controlled by an unknown party.
> 
> As he becomes comfortable with a given service, he gradually shares more details, such as his pending shopping requirements. This virtual shopping list is broken into categories and different parts are shared with different retailers depending on their specialty. The stores are able to notify Franklyn of any special offers, which he is free to ignore or take advantage of. 
> 
> Thanks to a promotional banner at a particular retailer's website, Franklyn learned he could get an extra discount on clothing because he is a military veteran. He gives that retailer a digital credential attesting to his status and links it to the DID they already have, securing the military discount for the rest of his relationship with them.
> 
> At any given time, he can cancel access to his data storage or simply revoke the DID entirely and either terminate the relationship or start over with a new DID.

**Comment by philarcher** [comment]
This has been done!
