### ISSUE TITLE
Psuedonymity rather than anonymity in Use Case 2.8

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-use-cases#111]
DIDs don't provide anonymity. That would require interactions that leave NO discernable identifier.

Instead, DIDs enable robust psuedonymity that enables desired correlatability without unnecessarily exposing confidential or private information. That is, you get the benefit of a useful identifier without the baggage of the rest of your identity.

Should be a minor fix.

**Comment by philarcher** [comment]
This has been done!
