### ISSUE TITLE
Use Cases document missing Terminology section

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#12]
The Use Cases document defines and uses a number of terms, but there's no Terminology section to systematically capture the definitions introduced.  Please add it and populate it.

One term that belongs in the Terminology section is "DID registry".  Another is "DID Method", as well as "DID Controller", "DID Subject", "Relying Party", and probably "DID" itself.

**Comment by peacekeeper** [comment]
We should be able to re-use the terminology section of DID core. It's in a separate file, so we should be able to just make a copy (or even directly reference?! - not sure if that would work) that file. It has all the terms you mention except "Relying Party".
https://github.com/w3c/did-core/blob/master/terms.html

**Comment by philarcher** [comment]
We might discuss this on the call today but I don't agree that the UCR should include content from the standard. The UCR informs development of the standard, not the other way round. I was making other changes to the doc while you were working on this and have copied your suggestions into the doc more or less verbatim. You can see the result at https://philarcher.github.io/did-use-cases/ for example. There's a PR for this but i suffers from the usual SNAFU so I need WG approval before 'resolving the conflicts'.

All being well, the UCR will be finished fairly quickly. It sets out the problem statement that the Core spec needs to address. Terms developed in the CCG are, of course, useful for discussing the topic and it would be very wrong to throw all that away, but the development of the normative spec *might* make changes to some terms and such changes need not be reflected in the UCR which, I hope, will be done and dusted in a matter of a few months (remember that docs published in TR space are immutable).
