### ISSUE TITLE
What does it mean for a DID to be "recorded in a registry"?

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#14]
3.1 Create says that "These DIDs are recorded in a registry...".  But there's isn't a clear explanation of what it means for the DID to be recorded, or what properties a registry has.

For instance, using database terminology, if the registry is a database, what consistency and/or atomicity and durability properties of the database entries are assumed and are necessary?

I suspect there's a lot behind these few words that bears fleshing out.

**Comment by jandrieu** [comment]
I'll try to clean this up in the FPWD, but might not be able to.

**Comment by OR13** [comment]
I would suggest removing the term registry parts. There are lots of methods such as `did:key` and `did:ethr`, `did:peer`, and non anchored sidetree dids don't require any registration.

**Comment by ken-ebert** [comment]
We need to consider did:peer and did:key as well.

**Comment by jricher** [comment]
It's entirely likely that "registry" isn't the right word for this piece of functionality. I don't have a better term off hand. But fundamentally it's about how a DID is tied to a DID document, which is part of the resolution process.

**Comment by jandrieu** [comment]
This deserves further discussion. We'll flag this term as under discussion for the FPWD.

**Comment by philarcher** [comment]
This issue is explicitly referenced from the current draft https://w3c.github.io/did-use-cases/#issue-container-number-14

**Comment by jandrieu** [comment]
We have a candidate for publication at https://w3c.github.io/did-use-cases/FPWD/2019-11-21/index.html

Once that is approved by the working group, we'll close out this issue.

**Comment by philarcher** [comment]
@jandrieu's last comment, from 2019-11-14, says we'll close this issue when FPWD is published - which happened. So I'm closing this!

**Comment by philarcher** [comment]
Closed by mistake. Apologies.

**Comment by jandrieu** [comment]
The question at the moment is where is the term "registry" in terms of the DID Document? Is that still a term in use? @msporny @talltree ?  I see "DID Registry" is still a term in use, is that stable or still in discussion?

**Comment by msporny** [comment]
> The question at the moment is where is the term "registry" in terms of the DID Document? Is that still a term in use? @msporny @talltree ? I see "DID Registry" is still a term in use, is that stable or still in discussion?

There is a PR in to change "DID Registry" to "Verifiable Data Registry". We plan to no longer use the term "DID Registry". The two terms that will be left in the spec after the most recent PRs go in are:

* Verifiable Data Registry (the place where DIDs are recorded)
* DID Specifications Registries (the place where developers go to find out what properties can be used in a DID Document, what DID Methods are available, etc.)

**Comment by jandrieu** [comment]
The only place that phrase is used is in Section 3 https://w3c.github.io/did-use-cases/#create:
> These DIDs may be recorded in a registry in such a manner as to be able to resolve to a DID Document. The DID Document may be dynamically and deterministically generated through resolution or it may be explicitly constructed as a stand-alone resource and either stored or referenced in the registry. In this scenario, the process will need access to any registry, ideally a decentralized system, and like the rest of the DID actions, it should be possible to create the DID without interaction with any particular authority.

This is an accurate statement. It doesn't assert that all DID methods record to a registry. In fact, the paragraph makes it clear that, for example, documents may be deterministically generated instead.

I do expect there is language in the did-core that refers to DID registries as an implied requirement (just because the language is out of date with some of the newer methods). However, the use case document itself avoids discussing the specifics of the design choices such as Methods and Registries as these are means to realize the use cases but not required for understanding the use.

@selfissued Does this address your concern?

I'd like to close this if it does.

**Comment by jandrieu** [comment]
Closing per WG conversation.
