### ISSUE TITLE
No reference for "the DID Resolution specification"

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#15]
Section 3.5 (Resolve) talks about "the DID Resolution specification" being under development but doesn't supply a reference to it.  (I'd also thought that DID Resolution was likely method-specific, and so there wouldn't be a single DID Resolution specification.)

Please clarify in the Use Cases document.

**Comment by peacekeeper** [comment]
+1 to including this reference in the Use Cases doc. The reference should be: https://w3c-ccg.github.io/did-resolution/.

You are correct that the actual process of obtaining a DID document for a DID is defined by the applicable DID method's ["Read" operation](https://w3c.github.io/did-core/#read-verify), but there are still some method-independent aspects that we can specify about resolving and dereferencing.

**Comment by jandrieu** [comment]
Will do.
