### ISSUE TITLE
Rotate operation section missing its section number

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#16]
The Rotate operation section comes between 3.7 (Verify Signature) and 3.8 (Modify Service Endpoint) but doesn't have its own section number.  Please correct this editorial issue.

**Comment by jandrieu** [comment]
We also saw this and fixed in Phil's rev. Will leave the issue open until the PR is ready & merged.

**Comment by jandrieu** [comment]
This has been fixed.
