### ISSUE TITLE
Clarify intent behind he language "When a DID contains a service name"

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#17]
Section 3.6 (Dereference) uses the language "When a DID contains a service name".  I believe that what's actually said is closer to the meaning "When a DID is accompanied by a service name parameter".  I know that there's a distinction between the base DID and parameters that can be added to it.

To the extent that this ability part of enabling Use Cases, this distinction should be clearly explained in the Use Case document.

**Comment by peacekeeper** [comment]
+1, this should be clarified to mention the `service` [generic parameter](https://w3c.github.io/did-core/#generic-did-parameter-names) that can be included in a DID URL.

The DID Resolution spec has a dedicated section about [dereferencing](https://w3c-ccg.github.io/did-resolution/#dereferencing).

**Comment by jandrieu** [comment]
Good catch. Will try to fix by FPWD.
