### ISSUE TITLE
Background statement in Decentralized Corporate Identifiers description not obvious

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#19]
Section 7.1.1 (Background) says "A great number of business to business and business to customer transactions could be executed more quickly and with greater assurance of the validity of the transaction if a mechanism to self-issue cryptographic identifiers were created."  It's not clear why this actually true.  The premise behind this assertion could use a more thorough description.

**Comment by jandrieu** [comment]
Good point. Will consider how to address that after FPWD.

**Comment by philarcher** [comment]
https://github.com/w3c/did-use-cases/pull/85 offered as a fix for this
