### ISSUE TITLE
Need to add coverage of portability/substitutability

### ISSUE THREAD

**Issue by burnburn** [w3c/did-use-cases#2]
Issue taken over from the CCG (https://github.com/w3c-ccg/did-use-cases/issues/10).

**Comment by jandrieu** [comment]
This needs greater discussion about what type of portability should be/could be supported by the DID spec.

**Comment by jandrieu** [comment]
Lets check to see if a use case addresses portability. 

My key question has always been what do we mean by portability? Moving a DID from one ledger to another? From one method to another? Is it about forwardability, i.e., an old DID pointing to a new DID, whose DID Doc that should be used instead?

Sounds like @talltree is going to draft a PR to suggest something.

**Comment by philarcher** [comment]
@talltree We'd like to close this issue but would welcome a PR from you if available in the next 14 days. Hope that's doable?

**Comment by philarcher** [comment]
No further discussion, well after 14 day notice period.

Closing.
