### ISSUE TITLE
Supply chain validation mechanisms not obvious in Decentralized Corporate Identifiers description

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#20]
Section 7.1.2 (Description) leaves the reader with a leap of faith:  How does the government associate the DIDs used with verified valid supply chain participants?  More explanation of how this is feasible and practical in a dynamic supplier network would help make this example more believable and comprehensible.

**Comment by jandrieu** [comment]
Good suggestion. I'd like to update after FPWD.

**Comment by philarcher** [comment]
https://github.com/w3c/did-use-cases/pull/85 offers fix for this as well
