### ISSUE TITLE
Long-life, recipient-managed credentials example doesn't say how the recipient can validate the issuer of the diploma

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#21]
Section 7.2 (Description) assumes that the recipient of the diploma data structure has a way of validating that Oxford was the issuer of the diploma, but doesn't say how that would be possible in practice, especially when Oxford could cease operation, lose accreditation, or be impersonated by another "Oxford".

It's also not clear what value using a DID is providing in this example, beyond carrying the diploma data structure signed by Oxford.

Again, this may seem like obvious stuff to those of you who have been living and breathing these specs for a while, but the actual description at least didn't make these things obvious to me, when I reviewed the spec.

**Comment by jandrieu** [comment]
Ok. That's a good comment. Not sure if we can resolve for FPWD, but what the DID is giving is SPECIFICALLY the ability to check the authority of the issuer even after they went out of business. You don't need Oxford's servers to check Oxford's DID.

Not sure what you mean about a DID "carrying the diploma data structure signed by Oxford". Could you unpack that a bit?

**Comment by philarcher** [comment]
https://github.com/w3c/did-use-cases/pull/85 offers a fix for this. Please note the comment in that specific commit.
