### ISSUE TITLE
Should "Althea" be "Alice" in the Prescriptions example?

### ISSUE THREAD

**Issue by selfissued** [w3c/did-use-cases#22]
In Section 7.3.2, Alice tells the online practice that her name is "Althea".  Is this an intentional example of a use of a pseudonym or a typo?

**Comment by jandrieu** [comment]
Good catch. These Alice & Bobs should all be replaced by alternative names. It looks like maybe we got started down that path and didn't finish the work.

**Comment by iherman** [comment]
Interestingly, I thought that was intentional, insofar as Alice did not want to use her own name in that privacy-sensitive case:-)

**Comment by agropper** [comment]
Yes. I used Althea as a pseudonym by Alice.

**Comment by selfissued** [comment]
If we're using pseudonyms, we need to be explicit for readers that that's what we're doing, so we don't cause confusing.  For instance, language like "Alice uses the pseudonym Althea in this transaction" would do the trick.

**Comment by jandrieu** [comment]
This should be fixed in PR #37

**Comment by philarcher** [comment]
Fixed
