### ISSUE TITLE
Tiny (mostly editorial) comments.

### ISSUE THREAD

**Issue by iherman** [w3c/did-use-cases#49]
- [ ] §2.1: "Online shopping, especially including 3rd party marketplaces creates" probably needs a comma after "marketplaces"
- [ ] §3, first paragraph: "...as intended in the DID Working Group Charter." refers to the time when the charter was still coming up. Maybe worth rephrasing this...
- [ ] §3.3 " DID is in fact its controller or specified as a Controller for a particular service endpoint. " I presume the first occurrence of "controller" should also capitalized (and possibly linked back to the terminology section?)
- [ ] §3.3 "allow for separate, proofs": isn't the comma superfluous?
- [ ] §3.4 " later be verified (#7 Signature Verification)" I presume the reference is to §3.7; not clear from the text
- [ ] §3.6 "When a DID is combined with a service parameter (forming a DID URL), dereferencing returns the resource pointed to from the named service endpoint, which was discovered by resolving the DID to its DID Document and looking up the endpoint by name....": this seems to be way too much details for a UCR document (and I am not sure the text in the paragraph is clear either...)

    I also have to say that the difference between §3.5 Resolve and §3.6 Dereference is not really clear in the text. The usual idea associated with a 'dereference' sounds the same as what is called 'resolve' here (Dereferencing a URL means that I get to the HTML file whose address it is). I think I understand the difference but the text needs some clarification imho. 
- [ ] §3.19 "controllers": should be capitalized and referenced to the terminology (I may have missed some other, typical cases in the section, better check...)
-  [ ] §4. introductory paragraph: I miss some form of a forward reference to the focal use cases. Reading the document so far there is only one use case, and a vague reference to "In collecting and evaluating potential use cases" and the feature/benefit grid comes a bit out of the blue. It may be useful to make it clear that this is some sort of synthesis, backed up by the focal use cases that are meant to be the representative use cases for the feature/benefit grid.
    
    Jumping ahead a bit, I also wonder whether the order of §6 and §7 should not be inverted. I read the document, get to the grid, I want to read the use cases and _then_ I can understand what §6 wants to say. Getting to §6 _before_ the focal use cases is fairly unclear.

**Comment by philarcher** [comment]
I've addressed many of these comments in https://github.com/w3c/did-use-cases/pull/54.
Personally, I strongly agree that the distinction between resolve and dereference is unjustified and confusing but I fear that you and may be in the minority, Ivan. If the two near-synonymous terms are retained then I'll defer to others to make a better distinction.
I'll talk to Joe about reordering the sections.

So this issue is *not* fully addressed by PR 54.
