### ISSUE TITLE
Focal use cases: more emphasis on DID-s?

### ISSUE THREAD

**Issue by iherman** [w3c/did-use-cases#50]
The title of the issue may be surprising, but reading the focal use cases I wonder whether these are use cases for Verifiable Credentials or for Decentralized Identifiers. In many cases (e.g., in §7.1 and §7.2) I have the impression that it is more the former than the latter.

I realize it is not always clear to separate the two, but the texts should nevertheless be revised to make it much clearer where the behaviour of DID-s come into play as opposed to emphasize the role of credentials.

**Comment by jandrieu** [comment]
We're open to suggestions for use cases that emphasize DIDs over VCs.

**Comment by jandrieu** [comment]
We've added a few use cases and a few more are in the pipeline that we believe help with this issue.

@iherman does this feel like good enough progress to close out this item?

**Comment by iherman** [comment]
I do, thanks. I am fine closing this issue.

**Comment by jandrieu** [comment]
Thanks! Closing.
