### ISSUE TITLE
New Use Case Proposals: 1) FMCG Intelligent Serial Number, 2) VIN DID, 3)Circular Economy

### ISSUE THREAD

**Issue by cstoecker** [w3c/did-use-cases#55]
DID as Intelligent Serial Number for FMCG objects (digital twinning), /Vehicles and Objects in the Circular Economy - DID cyber-physically linked to a product

1. FMCG Object Intelligent Serial Number (FMCG = Fast Moving Consumer Product)
2. VIN DID (VIN = Vehicle Identity Number), i.e. DID for your Car
3. Item Circular Economy (this is my preferred crown jewel use case of DIDs, because in a circular economy it is unpredictable which human or algorithm needs to interact with the circular item, to resolve the URL and to validate the life-cycle history of the object)

Questions to be answered:
- How to establish a DID for an object such as a Fast Moving Consumer Good 
- How to establish a vehicle DID in the human world (i.e. private key controlled by humans) as the Manufacturing Order is created to ensure back-to-birth traceability. 
- How to link the public key sitting in a vehicle telematics box as signing key to the DID document controlled by humans? Now the telematics box can do data attestation on behalf of the human controlled DID of the vehicle, Example of VIN DID (i.d. DID for Vehicle Identity Number)
- How to establish a cyber-physical link (recipe)?
- What is behind the service endpoint? Credential Store, Business Service Agent
- Short Value Proposition and new business use cases of Intelligent Serial Number for businesses
- Item in Circular Economy as further extension of the FMCG object digital twin

I will condense the content that is written here:

https://medium.com/spherity/ssi201-upgrading-products-with-intelligent-serial-numbers-and-dids-78da623b91dd

**Comment by cstoecker** [comment]
There is some evidence about the expected adoption of DIDs for use cases mentioned above:

1) Intelligent S/N, e.g. work by GS1, some spare part authenticity work by OEMs
2) VIN DID, work done by MOBI
3) Circular Economy, work being started by some enterprises to establish an audit trail about the Carbon Footprint of their products

We can nicely link this practical examples.

@philarcher : How should we proceed wrt/ the proposed use cases?

**Comment by bumblefudge** [comment]
Since I have recently done lots of editing on the medium article posted above and spent much of the last two weeks hashing out these ideas with Carsten, it would only take me/us a few hours to chop down the medium-article versions of 1, 2, and/or 3 into the format of the use-case document if there's interest.  In the coming week I could probably turn it around in 1-2 business days.

**Comment by philarcher** [comment]
Hi both,
Thanks for the pointer to the blog post - obviously interesting for a GS1 person (I'll gloss over some of the minor inaccuracies about what GS1 does and doesn't do ;-) ). Reading that and the above, I have drafted my reading of your use case, specifically the one around vehicle VINs. Please take a look at https://github.com/w3c/did-use-cases/pull/63.

You really see DIDs as serial numbers of FMCG? Or DIDs for batch/lot numbers? We should probably have a chat offline sometime as you're clearing working on cool stuff in GS1's area of interest.

**Comment by jandrieu** [comment]
Phil, what more should/might we do to adopt some of these?

**Comment by philarcher** [comment]
I've re-read the blog post with a view to extracting the other use cases (beyond the VIN). From a UCR perspective, the three use cases are all similar but the VIN one didn't mention recycling - i.e. a use *beyond* the life of the identified item. So I've added that in PR #90 

I suggest that, with this addition, the issue can be closed with thanks to Carsten and Spherity.

**Comment by jandrieu** [comment]
The addition in that PR looks good and we've merged it. https://github.com/w3c/did-use-cases/pull/90

@cstoecker @bumblefudge Is there more that you would like to see incorporated?

Or can we close this item?
