### ISSUE TITLE
Confusion about what a "DID" is throughout the document [DID Credentials]

### ISSUE THREAD

**Issue by mwherman2000** [w3c/did-use-cases#57]
In https://www.w3.org/TR/did-use-cases/#concepts-of-decentralized-identity, the text somewhat correctly defines what a DID is:
> A globally unique identifier that does not require a centralized registration authority because it is registered with distributed ledger technology (DLT) or other form of decentralized network. The generic format of a DID is defined in this specification. A specific DID scheme is defined in a DID method specification.

The majority of the rest of the document starts defining concepts like "DID Actions" ...which are not actions on a DID, the identifier, as defined in the above section of the document.  

There is a total mismatch here between a DID being a Decentralized Identifier and a DID not being a Decentralized Identity, i.e. a Credential consisting of a collection of Claims associated with a Subject by a Decentralized Identity.

ACTION: Need to separate out the actions against a Decentralized Identifier (a character string) vs. against a Decentralized Identity (a Credential).

**Comment by mwherman2000** [comment]
Checkout Appendix B of https://hyperonomy.com/2019/11/06/trusted-digital-web-whitepaper/ to get a deeper understanding about what a Decentralized Identifier is vs. a Decentralized Identity is.

**Comment by mwherman2000** [comment]
Here's a specific example of the "DID confusion" in section https://www.w3.org/TR/did-use-cases/#create :

> Controllers create DIDs, uniquely binding cryptographic proofs with the identifier, typically using public-private key-pairs. These DIDs are recorded in a registry in such a manner as to be able to resolve to a DID Document.

**Comment by mwherman2000** [comment]
I think the concept you're looking for is _DID Credential_ ...and by implication, _DID Credential Actions_. (Reference: https://hyperonomy.com/2019/11/30/trusted-digital-web-did-credential/)

![image](https://user-images.githubusercontent.com/6101736/69903010-58201e00-1351-11ea-816e-3b5f55d476e4.png)

**Comment by jandrieu** [comment]
This doesn't seem to apply.

**Comment by philarcher** [comment]
Overtaken by events...
