### ISSUE TITLE
Suggestion: Better partitioning of "DID" actions

### ISSUE THREAD

**Issue by mwherman2000** [w3c/did-use-cases#58]
In section https://www.w3.org/TR/did-use-cases/#actions of the document, it partitions the entire lifecycle about a "DID" (it's confused definition) into five categories: C.R.U.D. plus Use.

UPDATED: My suggestion is that it would be more useful to partition the collection of actions into a first category of those actions that essentially involve single role/actor and a DID Credential (defined here https://github.com/w3c/did-use-cases/issues/57#issuecomment-559989122) ...that is, simple operations like C.R.U.D. on a single DID Credential associated with single role/actor.  These are primary actions related to a single role/actor.  These actions are of interest to implementors and users of DID repositories/registries.

CORRECTED: The remaining actions (the second category) are those that involve the communication and verification of DID Credentials between two or more parties.  These actions are of interest to implementers and users involved with DID communication protocols and verification protocols that are implemented on top of the DID Credential repository/registry actions.

CORRECTED: The current organization (and associated diagram) is confusing for the above reason as well as the confusion in the overall document about what a DID is: a Decentralized Identifier (i.e. an string identifier) or Decentralized Identity (i.e. a Credential) .  You need to pick just one of these.

**Comment by TallTed** [comment]
> what a DID is: a Decentralized Identifier or Decentralized Identifier

Yes, that is confusing. Is it A or A?

> a DID stored in a repository/registry

A _DID_ may *lead* to a repository/registry, from which you will be able to retrieve a _DID document_, but the DID itself is just a URI, so the DID is not stored, as such.

**Comment by mwherman2000** [comment]
Thank you @TallTed.  I got tongue-tied trying to use the existing did-spec terminology to explain where the existing did-spec terminology is failing us here.  I've corrected the above as much as I can at the moment.  You really want to read the following reply first; https://github.com/w3c/did-use-cases/issues/57#issuecomment-559989122

**Comment by TallTed** [comment]
@mwherman2000 - I believe most of us in the current WG conversation have agreed that we're using `DID` only to abbreviate `Decentralized Identifier`.

I believe we're using `DID Document` for the singular concept I think you're calling variously `Decentralized Identity`, `DID Credential`, and `DID Document`, between which you seem to be differentiating based solely on how much detail they contain?

There are certainly blurred lines in the current text, referring to `DID` where it should be `DID document`, and vice versa.  We should correct these.

I don't think splitting hairs between the three variants of `DID document` is going to serve us, and I especially don't think it will be helpful to try to keep `Decentralized Identifier` straight from `Decentralized Identity` -- so I don't think the latter should be brought into the discussion.

**Comment by jandrieu** [comment]
Related to Issue #61 and PR #73 

@philarcher has a partial update to the SVG plus changes to the language (in separate efforts: the SVG is not in that PR).

**Comment by philarcher** [comment]
The current Editor's Draft (https://w3c.github.io/did-use-cases/#actions) makes an attempt to address this. Furthermore, at the time of  writing, new images have been created which can be seen at https://philarcher.org/temp/didDiagrams.html#actions. Those diagrams are still under review but show the direction of travel.

Unless we hear to the contrary @mwherman2000 within 14 days, @jandrieu and I will assume that we have met your issue and close this comment.

**Comment by jandrieu** [comment]
I have some more comments I'll put in email regarding those diagrams. We're getting there, but lets keep this open until we merge that PR.

@mwherman2000 If you could review what Phil's done and let us know if it's helping or missing the point, that would be appreciated.

**Comment by philarcher** [comment]
No further discussion on this topic for over a month. And substantial changes to the partitioning have been made. Closing.
