### ISSUE TITLE
New Use Case Proposal: Blending DIDs with X.509

### ISSUE THREAD

**Issue by cstoecker** [w3c/did-use-cases#59]
Blending existing X.509 certificates with DIDs enables faster adoption while using existing trust anchors

There are two ways to integrate DIDs with X.509:
![image](https://user-images.githubusercontent.com/12436209/69891394-8de6e780-12fc-11ea-9e82-bb82ffada595.png)

Use case will describe how the relation between DID and X.509 can be established.

**Comment by TallTed** [comment]
Consider also the X.509 [`Subject Alternative Name` (SAN)](https://tools.ietf.org/html/rfc5280#section-4.2.1.6), which is in current use with for [WebID Authentication over TLS](https://www.w3.org/2005/Incubator/webid/spec/tls/).

I see no reason that DIDs (being URIs) could not be placed in the SAN just like WebIDs (which are also URIs).

**Comment by dlongley** [comment]
> I see no reason that DIDs (being URIs) could not be placed in the SAN just like WebIDs (which are also URIs).

DIDs were designed to be compatible with WebID and to work just like this. We will need to be careful that a group decision doesn't cause us to unintentionally lose this compatibility because we haven't been explicit about it in the spec (yet).

See: https://github.com/w3c/did-core/issues/128

**Comment by cstoecker** [comment]
@TallTed @dlongley - Am I understanding you correctly that you 
1. support the use case of blending DIDs with X.509 should be added to the sample DID use cases?
2. And that we shall highlight linking a DID into a X.509 SAN?

The blending DIDs w/ X.509 mechanism can be quite similar to the WebID approach (which doesn't have much adoption yet, but it might make sense to reference the principle). If I understood the [w3c/did-core#128](https://github.com/w3c/did-core/issues/128) thread correctly we might lose WebID compatibility by moving to plain JSON. This is en entirely different discussion that should impact the use case proposed here (and that should be sorted out in Sam's thread).

**Comment by philarcher** [comment]
IMO, this potential use case is more of a discussion about a specific implementation. We have used DID terminology in the UCs, so we're not starting from scratch, but I think this one goes too far into solutioneering. The use case would have to be something along the lines of "If integrated with X.509, DIDs make operations ABC possible (that are currently either difficult or impossible)"

As @jandrieu  says - this would need a PR from @cstoecker to be included. I suggest it needs to be along the lines indicated here - or we'll close the issue.

**Comment by jandrieu** [comment]
I agree with @philarcher in that this feels very solution oriented rather than problem oriented, and hence not a good fit with the use case document. It might be better suited for the implementation guide.

@cstoecker I'd like to close this, but want to give you an opportunity to suggest a PR that is more focused on the problem.

Let us know if you want to put something together.

**Comment by philarcher** [comment]
No further input received, closing the issue
