### ISSUE TITLE
Decentralised Identity Resolution

### ISSUE THREAD

**Issue by ydennisy** [w3c/did-use-cases#67]
Hi,

I was wondering if the member of this group have given any thought to how identity resolution could work under this model, and if yes what is what are the key challenges and blockers.

With the demise of 3rd party cookies, many web publishers would be interested in how one can share opted in information about users across domains.

Is this a use case which you feel fits within the concept of DIDs?

Best,
Dennis

**Comment by philarcher** [comment]
Yes, @ydennisy, I think that's a key use case and have drafted some text that, I hope, addresses it. Please review and comment on https://github.com/w3c/did-use-cases/pull/72
