### ISSUE TITLE
Auto-inclusion of glossary from DID-Core

### ISSUE THREAD

**Issue by philarcher** [w3c/did-use-cases#75]
The current UCR automatically includes the terminology section from the DID-Core, which seemed like a good idea at the time. However, this text, not unreasonably given its provenance, includes phrases like "The generic format of a DID is defined in this specification" which are inappropriate in the UCR. Therefore I think the terminology section should be replaced with a simplified, static, version with words to the effect of "this is how we use these terms in this doc. Definitions may be updated in the DID-Core spec (link) in which case the definitions provided there should be seen as authoritative outside the specific context of this use cases document."

**Comment by jandrieu** [comment]
Hmmm. I think this needs further discussion. My expectation would be that we would push for changes to the common glossary rather than fork.

**Comment by jandrieu** [comment]
There's a way for the glossary to self-select the terms from those tagged as defined in the body of the text. 

Today, the glossary is including the term "verified timestamp", but that isn't used in the rest of the document.

@TzviyaSiegman Do you remember what we did with the VC Use Cases?

**Comment by jandrieu** [comment]
Note, we do use 
> data-oninclude="restrictReferences"

But it's not working.

We see errors that "did-resolution" and "did-url-dererferencing" are not in the glossary. Either we take out those terms or we add them to the glossary.

**Comment by philarcher** [comment]
Needs WG discussion and fixing the filtering of terms. Also, imported doc references terms in the core spec which don't apply in the UCR which is causing problems.  See core issue https://github.com/w3c/did-core/issues/311

**Comment by philarcher** [comment]
This was causing a lot of broken links in the doc as the source section in the Core Spec includes many references to other sections of that doc. So I have made a static copy, with a reference back to the dated (immutable) copy and said that in case of any discrepancy, the core spec is authoritative. I commented out the terms that do not appear in the UCR.
