### ISSUE TITLE
rename master branch

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-use-cases#88]
# Summary
We should rename the branch `master` to `main` and use that going forward for our work.

From [Problematic Terminology in Open-Source](https://blog.carbonfive.com/2018/10/08/problematic-terminology-in-open-source/) on master/slave terminology in software:

> Use of this term is problematic. It references slavery to convey meaning about the relationship between two entities.

Removing this terminology from our workflow is a small gesture to include more people from marginalized groups in this project.

(I’m open to names other than `main`)

## Technical Steps

- [ ]  create main branch from master
- [ ]  make main the default GitHub branch
- [ ]  modify github/central to use main for release notes reloading
- [ ]  redirect PRs to main in w3c/did-use-cases
- [ ]  move branch protections from master to main
- [ ]  modify docs to reference main instead of master
- [ ]  delete master branch to avoid confusion?

Feedback?

**Comment by iherman** [comment]
See my comment on https://github.com/w3c/did-core/issues/332#issuecomment-648238546. TL;DR: this step creates problems with the github.io paging mechanism.

**Comment by selfissued** [comment]
Please no.  This wouldn't just affect the primary repository.  This would affect every branch, every fork, and every local clone, requiring manual steps by all participants to make parallel changes to these copies.  The chances of everyone getting this right are close to zero.

Using git correctly is already complicated enough.  Please don't make this repository even more complicated than usual.

**Comment by dlongley** [comment]
My understanding is that github is working on tools to make this sort of transition easier. I support moving to the new name, but I recommend we wait until the tools are ready to make it an easy change and so that we don't duplicate effort.

**Comment by philarcher** [comment]
OK, so from this discussion, there's nothing to be done, at least for now. Putting this on the 'forget unless there's a reason to remember pile.

**Comment by brentzundel** [comment]
I'm fine with waiting to do this until tools to do so are provided by github, unless those tools aren't made available in 6 months.

**Comment by philarcher** [comment]
As discussed at the (virtual) F2F, there is no action to take for this issue. Closing now.

**Comment by brentzundel** [comment]
there will be steps to take, and I would like to keep this open as a reminder to take them when they are available

**Comment by brentzundel** [comment]
It looks like they're still working on tooling to make this easier: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-
but these should be in place by the end of the year.

**Comment by jandrieu** [comment]
We agree with this direction, but frankly, the editors aren't sure how to do this. It seems like it would need adjustments to echidna, which we have famously failed to do correctly. @iherman is this a task you can take care of?

**Comment by iherman** [comment]
Actually, I think I am the only one who take care of it (you need admin rights). We did it for the did-core, but I know @msporny had done some preliminary steps in merging and branching and all that jazz... @msporny do you still have the list for the steps we had to take?

(Actually... if we decide to publish the note for the use cases soon, I would expect this repository to go very quiet. Maybe we should wait until then...)

**Comment by philarcher** [comment]
Thanks to @iherman, this has been done.
