### ISSUE TITLE
Add WebAuthN use case

### ISSUE THREAD

**Issue by jandrieu** [w3c/did-use-cases#95]
Addressing use cases from #52

**Comment by OR13** [comment]
I did try and implement WebAuthN with DIDs... in particular, you can get public key material.... and signatures for the public keys... but they are all specific to authentication ....WebAuthN does not support vanilla signatures, you can't transfer bitcoin with it, or use it to build other cryptographic suites.... which is.... terrible...imo :)

**Comment by OR13** [comment]
You can register a public key, and a did, and then use the public key to authenticate the did.... but its a lot of work... and I found myself feeling like it was a waste of time without web authn supported raw digital signatures like i can get from Yubikey or Tangdem directly...

**Comment by agropper** [comment]
In https://github.com/w3c/did-core/issues/359#issuecomment-670838717 I asked about “attestation” related to authentication standards (WebAuthN, FIDO)
https://macsecurity.net/view/391-safari-14-will-introduce-face-id-and-touch-id-for-the-web
It includes:

> “To address known security issues, Apple engineers have masterminded a
> proprietary attestation service that laces each credential with a unique
> certificate.”

I seems relevant to this issue but I'm hoping for an example or use-case.

**Comment by jandrieu** [comment]
This hasn't gotten any traction. Closing if no futher discussion.

**Comment by arianvp** [comment]
Signing with Webauthn is definitely possible. It's literally all it does. It signs a random challenge. And server then checks if the signature is correct and the challenge is the same. Instead of making the challenge random you Just need to put the haab content of what you want to sign in the challenge parameter and a signature comes out of the contents comes out...
