### ISSUE TITLE
DIDComm and serviceEndpoints 

### ISSUE THREAD

**Issue by OR13** [w3c/did-use-cases#97]
Lets describe high level, the value of did comm, and how dids can be used to private communication.

**Comment by OR13** [comment]
ping @dhh1128 @tplooker

**Comment by dhh1128** [comment]
Where do you want this description? Here in the ticket?

**Comment by OR13** [comment]
@dhh1128 yes, lets start in the ticket, and once you feel its good, I'm happy to make a PR for your review.

**Comment by OR13** [comment]
Something like:

DIDComm is a suite of data formats and protocols for interoperable, authenticated, end to end encryption using decentralized identifiers.  DIDComm can be used to exchange sensitive information, including serviceEndpoints, which can be used to mediate further information exchange... `<concrete did comm use case>`

**Comment by dhh1128** [comment]
For reference, DIDComm v1's use of `serviceEndpoint` is documented here: https://github.com/hyperledger/aries-rfcs/blob/master/features/0056-service-decorator/README.md. And DIDComm's general purpose and application is documented here: https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0005-didcomm/README.md

Here is a tweak of what you started, Orie:

DIDComm is a low-level protocol for interoperable, authenticated, end to end encryption using decentralized identifiers. It is transport-agnostic, meaning it can run over HTTP(S), email, sockets, Bluetooth, AMQP, sneakernet, NFC, XMPP, Kafka, or any other mechanism that makes data flow. It is message-based and asynchronous. DIDComm can be used as a foundation for any high-level protocol exchange sensitive information. DIDComm is not API-centric, which means it doesn't need a different serviceEndpoint for each protocol.

**Comment by OR13** [comment]
I think we should provide an example of didcomm in action, and then this will be ready for a PR.

**Comment by dhh1128** [comment]
For examples, we could provide the following additional sentence:

>Some examples of problems solved by DIDComm-based protocols include [issuing credentials one-by-one](https://github.com/hyperledger/aries-rfcs/blob/master/features/0036-issue-credential/README.md) or in bulk, [exchanging a DIF presentation submission with a verifier](https://github.com/hyperledger/aries-rfcs/blob/master/features/0037-present-proof/README.md), [negotiating](https://github.com/hyperledger/aries-rfcs/blob/master/features/0075-payment-decorators/README.md) and finalizing payment, recovering a sharded secret, synchronizing the state of multiple mobile wallets, conducting a multi-player game, backing up and recovering personal data, [securely randomizing turn-taking](https://github.com/hyperledger/aries-rfcs/blob/master/features/0193-coin-flip/README.md), and so forth. 

Do we want hyperlinks for the examples?

**Comment by OR13** [comment]
@dhh1128 yes, hyperlinks for at least a few would be excellent... if we can focus on one that are "spanning" in the sense of explaining how didcomm works with services, i think that would be most helpful.

**Comment by dhh1128** [comment]
I updated my comment above with a few interesting hyperlinks.

**Comment by OR13** [comment]
excellent, I can take a stab at a PR for this.

**Comment by OR13** [comment]
PR is up.

**Comment by philarcher** [comment]
Taken care of with #139, closing.
