### ISSUE TITLE
Package Manager / App Store and Service Endpoints

### ISSUE THREAD

**Issue by OR13** [w3c/did-use-cases#98]

**Comment by OR13** [comment]
@csuwildcat to add you example to this issue, so we can work towards a PR.

**Comment by OR13** [comment]
Consider a world where nobody can be blocked from publishing, but only some apps come with an "Approved by Apple", "Approved by Microsoft" badge....

https://www.businessinsider.com/apple-refuses-to-allow-major-apps-from-microsoft-google-facebook-2020-8

**Comment by bumblefudge** [comment]
Paging Dr. @dhuseby

**Comment by jandrieu** [comment]
Awaiting PR for two months. Recommending closing unless we have further discussion. @OR13 is this still a use case you hope to get in before we close? Our goal is to have at least a draft final doc by Nov 2.

**Comment by OR13** [comment]
closing due to lack of response from @csuwildcat
